bdBundle\Entity\Productosobra:
    type: entity
    table: productosobra
    indexes:
        fk_productos_obras:
            columns:
                - obra_id
        fk_codprod:
            columns:
                - codprod
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        proveedor:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        albaran:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false            
        descripcion:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        und:
            type: integer
            nullable: true
            options:
                unsigned: false
        precio:
            type: float
            nullable: true
            precision: 10
            scale: 0
        oferta:
            type: float
            nullable: true
            precision: 10
            scale: 0
    manyToOne:
        codprod:
            targetEntity: Producto
            unique: false
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                codprod:
                    referencedColumnName: id
            orphanRemoval: false
        obra:
            targetEntity: Obra
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                obra_id:
                    referencedColumnName: id
            orphanRemoval: false
        prefijo:
            targetEntity: Prefijo
            unique: false
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                prefijo:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
