bdBundle\Entity\Producto:
    type: entity
    table: productos
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        prefijo:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        codprod:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        descripcion:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        precio:
            type: float
            nullable: true
            precision: 10
            scale: 0
    manyToMany:
        proveedores:
            targetEntity: Proveedor
            cascade: ["persist"]
    lifecycleCallbacks: {  }
