bdBundle\Entity\Proveedor:
    type: entity
    table: proveedores
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        codprov:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        proveedor:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false

    lifecycleCallbacks: {  }
